version: '3'
services:
  ui-library:
    build: .
    container_name: react-ui-library
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      NODE_ENV: development
    command: npm start
